### ISSUE TITLE
statement format

### ISSUE THREAD

**Issue by diana1357** [AskiaADX/adc2-responsiveTable#1]
Hi

Please reconsider the statement html format

Currently it is formatted as a link:
`<a class="display"> <span class="items">Item 1</span></a>`
 and it clashes with the template colours. Please change to a button so that the style can be set within the adc not from template css.

Also, please remove class "row" this class is in conflict with Boostrap:
`<tr data-id="U2" class="row">`

For example here it is how it looks in my survey:
![responsivetable](https://user-images.githubusercontent.com/20987595/31673062-1feae5a4-b356-11e7-84c7-abde0d4b176c.PNG)

Thanks in advance!

**Comment by Djedj** [comment]
Hi @diana1357 

Please add a small qex file to reproduce the problem

Best Regards

**Comment by Djedj** [comment]
Hi @diana1357 ,

The ResponsiveTable adc is updated to v2.0.3

Tell us if it makes the trick ?

Best Regards

**Comment by diana1357** [comment]
I have just checked and all looks good, thank you :+1:
