### ISSUE TITLE
Header font colour on mobile

### ISSUE THREAD

**Issue by diana1357** [AskiaADX/adc2-responsiveTable#3]
Hi 

When I use a dark background for the header, white font, and select "No" for "use header style first column", on mobile view, the font colour for the header is not working.

Desktop:
![desktop](https://user-images.githubusercontent.com/20987595/48636750-ad49f580-e9c3-11e8-9328-266ec1a7fb9d.JPG)
Mobile:
![mobile](https://user-images.githubusercontent.com/20987595/48636759-b20ea980-e9c3-11e8-8f83-63debef9d183.JPG)

**Comment by diana1357** [comment]
Hi!

Is there any update on this?

Thanks
Diana

**Comment by Djedj** [comment]
Hi @diana1357, 

I just updated the adc to v2.0.16.

Can you try and tell us i it makes the trick ?

Best Regards
